sqs/template.yaml
Set the production TxMA account, so that it can use the `AllowReadByTXMAAccount` policy.
Account id taken from `tech-ops-private` repo.
=> BAU Set production txma account

.github/workflows/post-merge-publish-txma-infrastructure.yaml
The TxMA workflow has been updated to fix an indentation error
This change has been made to correct the workflow so that the TxMA MQ infrastructure can be deployed
- [KBV-817](https://govukverify.atlassian.net/browse/KBV-817)
None
=> KBV-817 correct workflow_dispatch indentation.

.github/workflows/pre-commit.yml
=> Add precommit GHA

.github/workflows/post-merge-publish-core-infrastructure.yaml, .github/workflows/post-merge-publish-txma-infrastructure.yaml, .github/workflows/pre-commit.yml, .secrets.baseline
Workflows have been updated:
* Deprecated GHA actions have been updated to the newer versions.
* setup-sam fix has been applied
Primarily to apply the setup-sam fix so that the workflows are not broken.
(https://github.com/aws/aws-sam-cli/issues/4527)
Secondly in preparation for GitHub to remove the deprecated functionality.
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1146 workflow deprecations and sam fix

.github/workflows/post-merge-publish-core-infrastructure.yaml, .github/workflows/post-merge-publish-txma-infrastructure.yaml, .secrets.baseline
Added the DL dev environment
So that we have a dev environment in DL for pre merge integration tests
=> LIME-421: Adding the DL dev environment

.github/workflows/post-merge-publish-txma-infrastructure.yaml, txma/template.yaml
- [LIME-405](https://govukverify.atlassian.net/browse/LIME-405)
[LIME-405]: https://govukverify.atlassian.net/browse/LIME-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-405 - Increases SQS retention from 4 days to 7 days

.github/workflows/post-merge-publish-core-infrastructure.yaml, .github/workflows/post-merge-publish-txma-infrastructure.yaml, .github/workflows/pre-commit.yml, .secrets.baseline
Pinned versions of:
- Python
- SAM
Removed San fix step
- Prevent issues with auto updates from SAM
- Latest pinned version of SAM no longer requires fix
- [OJ-1275](https://govukverify.atlassian.net/browse/OJ-1275)
[OJ-1275]: https://govukverify.atlassian.net/browse/OJ-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OJ-1275] Pin software versions in all repos

.github/workflows/post-merge-publish-txma-infrastructure.yaml, .secrets.baseline
Added the dev account for the toy CRI to the github workflow
Need a txma-infrastructure stack in the toy dev cri account in order to deploy other resources
- [OJ-1396](https://govukverify.atlassian.net/browse/OJ-1396)
[OJ-1396]: https://govukverify.atlassian.net/browse/OJ-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1396 add toy dev to github workflow

.github/workflows/post-merge-publish-core-infrastructure.yaml, .secrets.baseline
Added toy build to the workflow
Updated core matrix to use dev-platform upload action
This change brings in the metadata for Grafana and other tooling
- [OJ-1517](https://govukverify.atlassian.net/browse/OJ-1517)
- [OJ-1520](https://govukverify.atlassian.net/browse/OJ-1520)
[OJ-1517]: https://govukverify.atlassian.net/browse/OJ-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1520]: https://govukverify.atlassian.net/browse/OJ-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update core matrix to use dev-platform upload action

txma/template.yaml
=> OJ-1663-b template error

txma/template.yaml
=> OJ-1663 revert unecessary changes

txma/template.yaml
IPS-588 IPS-600 IPS-601 IPS-602 IPS-603 IPS-604 TxMA SQS Queue Updates
Updated retention period for sqs queue.
modified:   txma/template.yaml
IPS-588 IPS-600 IPS-601 IPS-602 IPS-603 IPS-604 TxMA SQS Queue Updates
Updated retention period for sqs queue.
modified:   txma/template.yaml
- [IPS-588](https://govukverify.atlassian.net/browse/IPS-588)
[IPS-588]: https://govukverify.atlassian.net/browse/IPS-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-588 IPS-600 IPS-601 IPS-602 IPS-603 IPS-604 TxMA SQS Queue Updates  Updated retention period for sqs queue. modified: txma/template.yaml

txma/template.yaml
Add queue policy needed for CRIs that use step functions/event bus to allow the sending of events
Queues can only have one policy so policy statement needs to be added here
- [OJ-1851](https://govukverify.atlassian.net/browse/OJ-1851)
[OJ-1851]: https://govukverify.atlassian.net/browse/OJ-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1851: Add queue policy needed for CRIs that use step functions/event bus

txma/template.yaml
Adds `AuditEventDeadLetterQueuePolicy` so that event bridge can push to the DLQ
- [OJ-2337](https://govukverify.atlassian.net/browse/OJ-2337)
[OJ-2337]: https://govukverify.atlassian.net/browse/OJ-2337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 2337 process event to add to txma queue

README.md, RELEASE_NOTES.md
Adds RELEASE_NOTES
So that teams are aware of changes that are being released when they re-deploy without having to trawl through commit history
=> Adds RELEASE_NOTES

.github/workflows/post-merge-publish-core-infrastructure.yaml, .github/workflows/post-merge-publish-txma-infrastructure.yaml, .pre-commit-config.yaml, .secrets.baseline
updating devplatform-upload-action to v3.9.1
=>  updating devplatform-upload-action to v3.9.1

.github/workflows/kiwi-post-merge-publish-core-infrastructure.yaml
- Remove env from workflow name as this is already included in `matrix.target`
- Fix var name
- [IPS-1683](https://govukverify.atlassian.net/browse/IPS-1683)
[IPS-1683]: https://govukverify.atlassian.net/browse/IPS-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1683: Kiwi workflow fixes

core/template.yaml
- Fix type (Duplicate Conditions)
=> BAU: Fix conditions

core/template.yaml
- Added ignore checks (these are set in the pipeline, but default to none in the template)
- `[[E3031: Check if property values adhere to a specific pattern] ('none' does not match 'arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\\d{1}:\\d{12}:code-signing-config:csc-[a-z0-9]{17}') matched 23, [E3033: Check if a string has between min and max number of values specified] ('none' is shorter than 20) matched 28]
Error: Linting failed. At least one linting rule was matched to the provided template.`
- `[[E3033: Check if a string has between min and max number of values specified] ('none' is shorter than 20) matched 34]
Error: Linting failed. At least one linting rule was matched to the provided template.`
=> Fix cfn-lint

README.md
Updated readme how to deploy changes into each service
Improved clarity
=> BAU readme how to deploy changes

core/template.yaml
Remove SessionTable1
This table has never been used, by any of the CRI's there is a SessionTable in the common-lambda stack
Clean up unused resources
- [OJ-3344:](https://govukverify.atlassian.net/browse/OJ-3344:)
=> OJ-3344: Removed SessionTable1

core/template.yaml
Reverts govuk-one-login/ipv-cri-common-infrastructure#134
=> Revert "OJ-3344: Removed SessionTable1"

core/template.yaml
Reverts govuk-one-login/ipv-cri-common-infrastructure#136
=> Revert "Revert "OJ-3344: Removed SessionTable1""
