govuk-one-login/ipv-cri-common-infrastructure

.github/workflows/post-merge-publish-core-infrastructure.yaml
.github/workflows/post-merge-publish-txma-infrastructure.yaml

Removed the Driving Licence from common infra dev 
Because DL does not have a distinct development environment
- [LIME-160](https://govukverify.atlassian.net/browse/LIME-160)

LIME-160: Removed dev until a dev environment can be added for DL

---

core/template.yaml

Add infrastructure to support CloudWatch Alarms sending events to SNS.
Add an SNS Topic and a pagerduty subscriber to the topic. Export the Topic Arn to be used by dependent stacks.
🚨 Each affected AWS account will need to have the SSM param `/alerting/pagerduty/url` set prior to deploying this stack.
- [OJ-1002](https://govukverify.atlassian.net/browse/OJ-1002)

OJ-1002 feat: SNS topic and subscription for sending alerts

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
.github/workflows/post-merge-publish-txma-infrastructure.yaml
.secrets.baseline

The CIC CRI is added to the list of CRIs in the GitHub post-merge-publish-core-infrastructure workflow and the post-merge-publish-txma-infrastructure workflow. 
New secrets are referenced, which will need to be added to this repo. 
New CRI needed to be added to common infrastructure workflows.
[F2F-135](https://govukverify.atlassian.net/browse/F2F-135)

F2F-135: Adding the CIC CRI to the GitHub workflows

---

txma/template.yaml

Added message retention period for SQS queue.
Increased from the default of 4 days to 7 days.
- [LIME-405](https://govukverify.atlassian.net/browse/LIME-405)
[LIME-405]: https://govukverify.atlassian.net/browse/LIME-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-405 - Increased retention period from 4 days to 7 days

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
.github/workflows/post-merge-publish-txma-infrastructure.yaml
.secrets.baseline

Passport CRI DEV and BUILD deployments configurations added to post-merge action
To align passport CRI with common-cri best practices
- [PLAT-811](https://govukverify.atlassian.net/browse/PLAT-811)
Secure pipeline secrets similar to existing CRIs 
[PLAT-811]: https://govukverify.atlassian.net/browse/PLAT-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLAT-811: Passport CRI in post-merge GHA

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
.github/workflows/post-merge-publish-txma-infrastructure.yaml

The configure-aws-credentials action v1-node16 was failing due to a node12 reference which is no longer supported by GitHub. Version 2 has been released last week which resolves this issue. 
To fix the failing workflows
- [OJ-1346-](https://govukverify.atlassian.net/browse/OJ-1346)

fix: update configure-aws-credentials to v2

---

dns-records/template.yaml
dns-zones/template.yaml

Replaced hardcoded references belonging to Address CRI with parameters
Allowing both dns-zones and dns-records templates to be usable to any future CRI to install the components
- [PLAT-833](https://govukverify.atlassian.net/browse/PLAT-833)
[PLAT-833]: https://govukverify.atlassian.net/browse/PLAT-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLAT-833: DNS Zones and records template

---

.github/workflows/post-merge-publish-txma-infrastructure.yaml
.secrets.baseline

Added toy build to the workflow
Updated txma matrix to use dev-platform upload action
This change brings in the metadata for Grafana and other tooling
- [OJ-1518](https://govukverify.atlassian.net/browse/OJ-1518)
- [OJ-1521](https://govukverify.atlassian.net/browse/OJ-1521)
[OJ-1518]: https://govukverify.atlassian.net/browse/OJ-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1521]: https://govukverify.atlassian.net/browse/OJ-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update txma matrix to use dev-platform upload action

---

txma/template.yaml

Allow each account to consume messages from their own txma audit event queue
To prevent txma from being overwhelmed by messages when performance testing of the CRIs begins, we've created a lambda to consume the messages however this lambda needs permission to do so
- [OJ-1663](https://govukverify.atlassian.net/browse/OJ-1663)
[OJ-1663]: https://govukverify.atlassian.net/browse/OJ-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1663 enable root account access for audit queue consumers

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
.github/workflows/post-merge-publish-txma-infrastructure.yaml
.secrets.baseline

Added configurations for HMRC
Added deployment enablement flags as repository variables
Re-added fraud which had gone missing from the dev deployments
These changes allow deployment to specific targets and enable HMRC deployments for Dev and Build and re-introduce fraud dev.
- [OJ-1839](https://govukverify.atlassian.net/browse/OJ-1839)
- [OJ-1853](https://govukverify.atlassian.net/browse/OJ-1853)
[OJ-1839]: https://govukverify.atlassian.net/browse/OJ-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1853]: https://govukverify.atlassian.net/browse/OJ-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

oj-1839 hmrc txma and core matrix builds plus enablement toggles

---

txma/template.yaml

The permissions for kms:decrypt and kms:GenerateDataKey were set on the SQS Queue not the KMS key so it wasn't applying the permissions.

OJ-1851: Fix permissions for event bridge

---

txma/template.yaml

Make the TxMA queue in dev environments a mock queue so it can be used for audit event testing.
TxMA is only used in staging and higher environments, however, the build environment queues continue to be redirected to the TxMA stating environment.

OJ-2546: Disable TxMA event consumption in dev

---

txma/template.yaml

Cloudformation during deployment to non-dev accounts was failing due to malformed permissions on AuditEventQueueEncryptionKey

Fix permission formatting on AuditEventQueueEncryptionKey

---

RELEASE_NOTES.md
txma/template.yaml

Include `AuditEventDeadLetterQueue.Arn` in outputs 
So that it can be used by NINo for the `TxMaAuditEventRule` `DeadLetterConfig`
- [OJ-2618](https://govukverify.atlassian.net/browse/OJ-2618)
[OJ-2618]: https://govukverify.atlassian.net/browse/OJ-2618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2618: Exports the AuditEventDeadLetterQueue.Arn

---

txma/template.yaml

Exports `AuditEventQueueArn` 
Test harness needs it for event trigger
- [OJ-2735](https://govukverify.atlassian.net/browse/OJ-2735)
[PR where this output is being used ](https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/337)
[OJ-2735]: https://govukverify.atlassian.net/browse/OJ-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2735: Exports AuditEventQueueArn for the test harness

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
.secrets.baseline
core/template.yaml

Creating PublishedKeysS3Bucket which will be used by the key rotation stack. This bucket stores the published keys and the key rotation stack publishes new keys to this bucket, and replaces/ removes old ones.
Added deployment to idsre dev account as also need this bucket in idsre account.
Linked PR for key rotation stack which is removing the bucket and importing the bucket from [common-infrastructure] (https://github.com/govuk-one-login/identity-key-rotation/pull/64)
Bucket needs to be stored separately to the key rotation stack.
- [IPS-1506](https://govukverify.atlassian.net/browse/IPS-1506)
secrets variables added in order to deploy to idsre account
[IPS-1506]: https://govukverify.atlassian.net/browse/IPS-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

Ips 1506 key rotation bucket

---

core/template.yaml

- Include `StackName` in export name
- Avoid `An export with this name already exists` error when deploying stacks in dev
- Align with naming convention of other exports (both Orange and Lime do use the same stack name of `core-infrastructure`)
- [IPS-1529](https://govukverify.atlassian.net/browse/IPS-1529)
[IPS-1529]: https://govukverify.atlassian.net/browse/IPS-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1529: Update export names

---

core/template.yaml

- Add bucket policy. Its permissions statements are:
1.  Delegate IAM Access for Root Access
2. Bucket permissions: Allow APIGW and Lambda to `ListBucket` if they have the use tag (also allow if manage)
3. Object permissions: Allow APIGW and Lambda to `GetObject` if they have the use tag (also allow if manage)
4. Deny access if not using SecureTransport
- Add lambda role:
1. Can only be assumed by a resource:
a. With the tag `key_consumer_type`: `manage`
b. In the same AWS account
- Moved from key-rotation stack to this repo: https://github.com/govuk-one-login/identity-key-rotation/pull/81
- [IPS-1529](https://govukverify.atlassian.net/browse/IPS-1529)
[IPS-1529]: https://govukverify.atlassian.net/browse/IPS-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

IPS-1529: Add bucket policy

---

core/template.yaml

- Updated bucket policy (covers points 2-4 below) so only tagged resources/roles can access the bucket
- Removed extra role that lambda execution role would've originally assumed
In order for the lambda role to be able to write to the bucket, we need:
1. Explicit allow on identity policy for lambda role: https://github.com/govuk-one-login/identity-key-rotation/pull/98
2. Explicit allow on bucket policy
To limit access to resources with the tags `manage` or `use` we need:
3. Point number 2 above to be conditional on the tags
4. Explicit deny on bucket policy if tags not present or wrong
Policy statements:
1. Delegate IAM access (copied from SPOT)
2. Allow read permissions for the bucket and object, only if:
Service is APIGW/lambda
Tag is `use/manage`
3. Deny Read permissions in 2. if tag …

IPS-1529: Update bucket policy

---

.github/workflows/post-merge-publish-txma-infrastructure.yaml
.secrets.baseline

- Removed TOY accounts from deployment workflow
- TOY has been decommissioned
- [IPS-1635](https://govukverify.atlassian.net/browse/IPS-1635)
[IPS-1365]: https://govukverify.atlassian.net/browse/IPS-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-1635]: https://govukverify.atlassian.net/browse/IPS-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1365: Remove Toy from deployment workflow

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
.secrets.baseline

- Add `cic-dev` to deploy core-infra workflow
- Kiwi are migrating over from their L2 stacks to common-infrastructure
- [IPS-1608](https://govukverify.atlassian.net/browse/IPS-1608)
[IPS-1608]: https://govukverify.atlassian.net/browse/IPS-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1608: Deploy core infrastructure to cic-dev

---

core/template.yaml

- Updated bucket name
- Minimise probability of the bucket name being taken, as all S3 bucket names must be globally unique
- [IPS-1633](https://govukverify.atlassian.net/browse/IPS-1633)
[IPS-1633]: https://govukverify.atlassian.net/browse/IPS-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1633: Update bucket name

---

.github/workflows/post-merge-publish-core-infrastructure.yaml
core/package.json

Move esbuild to dependencies
Update sam version in deploy to build
esbuild is not being pulled in a as part of the sam build, moving esbuild to dependencies should correct this.
sam version was update in deploy to dev but not build
- [LIME-1664](https://govukverify.atlassian.net/browse/OJ-1664)
[LIME-1664]: https://govukverify.atlassian.net/browse/LIME-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1664 Move esbuild to dependencies and update sam versions in deploy to build

---

.github/workflows/kiwi-post-merge-publish-core-infrastructure.yaml
.github/workflows/post-merge-publish-core-infrastructure.yaml
.secrets.baseline
core/template.yaml

Add secure pipeline permission boundary, 
Add codesigning arn
Use separate output directory for code building
Added code signing name variable to git hub, 
- only lime CRI values set due to access limitations
(Updated KIWI action to follow - but untested)
Permission boundary required for the lambda role creation/
The lambda code is required to be signed.
Due to the addition of a lamdba reusing the project directory results in source code getting uploaded, a separate output directory is needed.
Code signing name variables - needed for the new lambda in the secure pipeline
(KIWI action needs the same changes - but untested)
- [LIME-1664](https://govukverify.atlassian.net/browse/LIME-1664)
[LIME-1664]: https://govukverify.atlassian.net/browse/LIME-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

LIME-1664 Add secure pipeline, codesigning and use separate output directory for code building

---

core/README.md
core/template.yaml

- Add `ObjectLock` to keys bucket
- Set to`COMPLIANCE` mode in prod and `GOVERNANCE` in lower envs (for feature parity in development, as advised the RFC)
<kbd>
</kbd>
- As outlined in the RFC: https://govukverify.atlassian.net/wiki/spaces/DID/pages/5014224958/OAuth+Encryption+Signing+Keys+-+Scope
> The RFC describes the use of ObjectLock in compliance mode on s3 objects for production level resiliency. This allows for a fix forward approach only, with each new revision being immutable and fully auditable. This is a security requirement for production level environments. Non-production environments may use Governance mode. Development environments may choose whether to enable Object Lock at all. 
> Aiming for feature parity in development is advised for greater confidence in the developed …

IPS-1598: Add Object Lock to keys bucket

---

core/template.yaml

Removed import of OAuthGenerationFunctionRoleArn and instead hard coding the value OAuthGenerationFunctionRole and including a wildcard
To remove coupling of the stacks
Currently the role can be called something like {StackName}-{LogicalResourceId}-{RandomString}
e.g. 
key-rotation-OAuthGenerationFunctionRole-3gr5gsdg4
Test:
Alarm notification sent when I updated the bucket with a different role - remove-contents-of-key-bucket-role-XXX but no notifications sent when I updated the bucket with the existing role
- [IPS-1956](https://govukverify.atlassian.net/browse/IPS-1956)
[IPS-1956]: https://govukverify.atlassian.net/browse/IPS-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1956 removed import value and defined it with a wildcard at the end
